### PR TITLE
fix(components/paginator): fixed `PrizmPaginatorComponent` instance was incompatible with `PrizmDataSource.paginator`

### LINKED ISSUE #1746: [BUG] @prizm-ui/components - `PrizmPaginatorComponent` instance incompatible with `PrizmDataSource.paginator` property
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Компонент

_PrizmPaginatorComponent_

### Скрин / Видео проблемы

image

### PR DESCRIPTION
**Pull request by AleksandrSibiakov**
fix(components/paginator): fixed `PrizmPaginatorComponent` instance was incompatible with `PrizmTableDataSource.paginator` property

resolved #1746

Also, for the PrizmTableDataSource, some properties in related interfaces were marked as read-only because they are not intended to be changed.

### CODE REVIEW

**Review by ZurabDev — APPROVED** [review]
LGTM

File: libs/components/src/lib/components/table/data-source.ts [hunk 1]
```diff
@@ -1,6 +1,5 @@
 import { DataSource } from '@angular/cdk/collections';
-import { BehaviorSubject, combineLatest, merge, Observable, of, Subject, Subscription } from 'rxjs';
-import { map } from 'rxjs/operators';
+import { BehaviorSubject, combineLatest, map, merge, Observable, of, Subject, Subscription } from 'rxjs';
```
Comment (ickisIckis) [inline libs/components/src/lib/components/table/data-source.ts:2]: Нет лишних импортов?

Comment (AleksandrSibiakov) [reply libs/components/src/lib/components/table/data-source.ts:2]: Нет. Чекнул юзаджи - все используется
